Repository dream11/vertx-aerospike-client, pull requests merged in 2021-08, with the labels that each got.

#20 fix: remove client instance from shared data on close()
  src/main/java/io/d11/aerospike/client/AerospikeClient.java
  src/main/java/io/d11/aerospike/client/impl/AerospikeClientImpl.java
  src/main/java/io/d11/aerospike/util/SharedDataUtils.java
Labels: code-changed, fix

#18 updated readme and javadoc configuration
  README.md
  pom.xml
Labels: documentation, maintenance

#21 ci: update and rename draft-and-bump.yml to release-drafter.yml
  .github/workflows/draft-and-bump.yml
  .github/workflows/release-drafter.yml
Labels: ci, maintenance
