Repository dream11/vertx-aerospike-client, pull requests merged in 2021-07, with the labels that each got.

#7 chore: add usage and configuration in README
  README.md
Labels: documentation, maintenance

#10 Tests Setup
  .github/workflows/ci.yml
  pom.xml
  src/test/java/com/dream11/aerospike/AerospikeConnectionTest.java
  src/test/java/com/dream11/aerospike/Setup.java
  src/test/resources/logback-test.xml
Labels: ci, code-changed, maintenance

#9 chore: move documentation to interface
  src/main/java/com/dream11/aerospike/client/AerospikeClient.java
  src/main/java/com/dream11/aerospike/client/AerospikeClientImpl.java
Labels: code-changed, maintenance

#8 Code Refactoring and Tests
  .github/workflows/ci.yml
  README.md
  pom.xml
  src/main/java/com/dream11/aerospike/client/AerospikeClient.java
  src/main/java/com/dream11/aerospike/client/AerospikeClientImpl.java
  src/main/java/com/dream11/aerospike/config/AerospikeConnectOptions.java
  src/main/java/com/dream11/aerospike/factory/AerospikeClientFactory.java
  src/main/java/com/dream11/aerospike/factory/AerospikeClientFactoryImpl.java
  src/main/java/com/dream11/aerospike/util/PolicyUtil.java
  src/main/java/com/dream11/aerospike/util/SharedDataUtils.java
  src/test/java/com/dream11/aerospike/AerospikeAddTest.java
  src/test/java/com/dream11/aerospike/AerospikeAppendTest.java
  src/test/java/com/dream11/aerospike/AerospikeConnectionTest.java
  src/test/java/com/dream11/aerospike/AerospikeDeleteTest.java
  src/test/java/com/dream11/aerospike/AerospikeExistsTest.java
  src/test/java/com/dream11/aerospike/AerospikeGetHeaderTest.java
  src/test/java/com/dream11/aerospike/AerospikeGetTest.java
  src/test/java/com/dream11/aerospike/AerospikeOperateTest.java
  src/test/java/com/dream11/aerospike/AerospikePrependTest.java
  src/test/java/com/dream11/aerospike/AerospikePutTest.java
  src/test/java/com/dream11/aerospike/AerospikeQueryTest.java
  src/test/java/com/dream11/aerospike/AerospikeScanTest.java
  src/test/java/com/dream11/aerospike/Constants.java
  src/test/java/com/dream11/aerospike/Setup.java
  src/test/resources/init.aql
  src/test/resources/logback-test.xml
Labels: ci, code-changed, maintenance, test

#12 Feat/release
  .ci/scripts/bump-version.sh
  .github/workflows/release.yml
  pom.xml
Labels: ci, feature, maintenance

#13 Update release.yml
  .github/workflows/release.yml
Labels: ci, fix, maintenance

#14 fix: codecov path in README
  README.md
  docs/index.md
  pom.xml
Labels: fix, maintenance

#15 chore: bump version and update README
  .ci/scripts/bump-version.sh
  README.md
  docs/index.md
  pom.xml
Labels: maintenance
